// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_magaling = "CgkIys3Bz5EeEAIQAw"; // <GPGSID>
        public const string achievement_para_po = "CgkIys3Bz5EeEAIQCw"; // <GPGSID>
        public const string achievement_amai = "CgkIys3Bz5EeEAIQBw"; // <GPGSID>
        public const string achievement_hey_whats_up = "CgkIys3Bz5EeEAIQCA"; // <GPGSID>
        public const string achievement_masarap = "CgkIys3Bz5EeEAIQBA"; // <GPGSID>
        public const string leaderboard_leaderboard = "CgkIys3Bz5EeEAIQAQ"; // <GPGSID>
        public const string achievement_grabeehhh = "CgkIys3Bz5EeEAIQBg"; // <GPGSID>
        public const string achievement_konichiwa = "CgkIys3Bz5EeEAIQAg"; // <GPGSID>
        public const string achievement_grabeh_grabeh = "CgkIys3Bz5EeEAIQCg"; // <GPGSID>
        public const string achievement_kumusta = "CgkIys3Bz5EeEAIQBQ"; // <GPGSID>
        public const string achievement_what_you_recommend = "CgkIys3Bz5EeEAIQCQ"; // <GPGSID>

}

